const tintColorLight = '#2f95dc';
const tintColorDark = '#5b9cf0';

export default {
  light: {
    text: '#111827',
    background: '#f1f5f9',
    tint: tintColorLight,
    tabIconDefault: '#9ca3af',
    tabIconSelected: tintColorLight,
    // Semantic tokens for consistent dark mode
    card: '#ffffff',
    border: '#e5e7eb',
    muted: '#6b7280',
    mutedSecondary: '#9ca3af',
    placeholder: '#9ca3af',
    inputBg: '#ffffff',
    inputBgDisabled: '#f3f4f6',
    buttonPrimary: '#2563eb',
    buttonPrimaryText: '#ffffff',
    buttonSuccess: '#22c55e',
    buttonSuccessText: '#ffffff',
    buttonDanger: '#dc2626',
    buttonDangerText: '#ffffff',
    error: '#dc2626',
    link: '#2563eb',
    headerBg: '#f8fafc',
    warningBg: '#fef3c7',
    warningBorder: '#f59e0b',
    warningText: '#92400e',
    photoButtonBg: '#e2e8f0',
    thumbBg: '#f1f5f9',
  },
  dark: {
    text: '#f1f5f9',
    background: '#1c1f2e',
    tint: tintColorDark,
    tabIconDefault: '#6b7280',
    tabIconSelected: tintColorDark,
    card: '#252836',
    border: '#3d4152',
    muted: '#94a3b8',
    mutedSecondary: '#64748b',
    placeholder: '#64748b',
    inputBg: '#2d3142',
    inputBgDisabled: '#252836',
    buttonPrimary: '#3b82f6',
    buttonPrimaryText: '#ffffff',
    buttonSuccess: '#22c55e',
    buttonSuccessText: '#ffffff',
    buttonDanger: '#ef4444',
    buttonDangerText: '#ffffff',
    error: '#f87171',
    link: '#60a5fa',
    headerBg: '#252836',
    warningBg: '#422c1a',
    warningBorder: '#f59e0b',
    warningText: '#fcd34d',
    photoButtonBg: '#3d4152',
    thumbBg: '#2d3142',
  },
};
